### ISSUE TITLE
QGis 3.4 - data and data model

### ISSUE THREAD

**Issue by gsollberger** [opengisch/qfieldsync#94] opened 2018-10-29 13:25 UTC
Hi,
Using QGis 3.4.0 and QFiled Sync 1.0.0 some problem appears when QField project.
Initial QGis project connected to postgres/postgis --> QField project connected to geopackage, the data and the database model are "shifted" ... see images below 
![qgis-data-postgres](https://user-images.githubusercontent.com/4537306/47652480-5a301000-db86-11e8-8f17-e43d9987cc3e.png)
![qgis-data-geopackage](https://user-images.githubusercontent.com/4537306/47652481-5ac8a680-db86-11e8-826f-1df33c4b8fab.png)

Any idea ?

Thanks and best regards.

Gérard Sollberger
HKD Géomatique Vaud SA - Nyon
www.geocommunes.ch

**Comment by m-kuhn** [comment] 2018-10-29 13:31
@signedav probably related to the fid column in geopackages?

**Comment by germain83** [comment] 2018-10-29 13:35
Hello,

I have exactly the same problem since qgis update

**Comment by germain83** [comment] 2018-10-29 13:37
on the other hand before the update qfield exported in sqlite

**Comment by signedav** [comment] 2018-10-30 06:40
I could not reproduce yet. I've seen a similar issue during the implementation of the offline_editing bugfix (https://github.com/qgis/QGIS/pull/7909#issuecomment-430926260) in case there have been an "fid" column in the online project but anyway this is fixed with the generated fid.

**Comment by signedav** [comment] 2018-10-31 08:13
Is it possible to provide a slim project to reproduce @germain83 @gsollberger ?

**Comment by germain83** [comment] 2018-11-05 08:41
[test_terrain_github_not_ok.zip](https://github.com/opengisch/qfieldsync/files/2547475/test_terrain_github_not_ok.zip)
[test_terrain_github_ok.zip](https://github.com/opengisch/qfieldsync/files/2547476/test_terrain_github_ok.zip)
not ok : QGIS 3.4.1
ok : QGIS 2.18.25

**Comment by signedav** [comment] 2018-11-06 06:32
Hi @germain83 Thanks for the project. When I run them I can see what's the problem. But for debugging I cannot reproduce. On my projects unluckily it seems to work. So would it be possible to receive a small db-dump, with the not (yet) exported layers. Of course it could be a dummy as well. Thanks a lot.

**Comment by germain83** [comment] 2018-11-06 09:39
Hi @signedav, 
My Postgres version is 10. 
This is not exactly the bdd because I have default values ​​based on sequences in other schemas
[bdd_github.zip](https://github.com/opengisch/qfieldsync/files/2552470/bdd_github.zip)

**Comment by signedav** [comment] 2018-11-06 10:34
Thanks @germain83 What version of QFieldSync do you use?

**Comment by germain83** [comment] 2018-11-06 12:44
3.0.3

**Comment by RNanclares** [comment] 2018-11-13 15:47
I'm seeing a similar bug in 3.4.1. Exporting a layer (shapefile with gid field) all columns get shifted one place to the right when fid field is added in the gpkg.  The values previously stored in the gid field are now stored in the next field to the right.
![imagen](https://user-images.githubusercontent.com/11431207/48424742-dc910600-e728-11e8-858b-e46513a8478b.png)

**Comment by m-kuhn** [comment] 2018-11-13 15:49
Upstream issue
https://issues.qgis.org/issues/20276

**Comment by saemiw** [comment] 2018-11-14 08:53
I confirm the issue.

**Comment by signedav** [comment] 2018-12-11 10:18
This should be solved by the integration https://github.com/qgis/QGIS/pull/8600 on master and https://github.com/qgis/QGIS/pull/8645 on 3.4.

Tell me, if you can confirm @saemiw @gsollberger @germain83 @RNanclares 

Thanks.

**Comment by saemiw** [comment] 2018-12-13 16:32
Does this mean its already testable in the nighly build of the developers branch (3.5.0-38) or should we await the release of 3.4 for testing?

**Comment by m-kuhn** [comment] 2018-12-13 16:45
3.5.0 and 3.4 nightly builds can be used for testing.
First stable releases will be 3.4.3 and later on 3.6

**Comment by germain83** [comment] 2019-01-09 11:20
it's good for me. Thanks

**Comment by m-kuhn** [comment] 2019-01-09 11:21
Thanks for the feedback

**Closed by m-kuhn** 2019-01-09 11:21 UTC

**Comment by signedav** [comment] 2019-01-09 11:24
Thanks guys :+1:

**Comment by gsollberger** [comment] 2019-01-09 15:41
OK for me, thanks for fix.
Gérard
