### ISSUE TITLE
Configurable picture path not saved

### ISSUE THREAD

**Issue by dortegat** [opengisch/qfieldsync#413] opened 2022-04-10 16:42 UTC
Image path settings are not saved when we modify them and exit and reopen the current project settings.

![image](https://user-images.githubusercontent.com/24475553/162630064-6ff6a806-55c0-49d2-9abb-4136a8fe238e.png)

Modify...
![image](https://user-images.githubusercontent.com/24475553/162630118-7860ec4d-d7c9-45ca-a8c2-1b94512e6b0a.png)

When I open properties again it saves the original route, not the modified one

**Comment by suricactus** [comment] 2022-04-11 11:22
Sorry to ask, but did you press "Apply" or "Ok" before closing the window? If not, please give more details about QGIS, QFieldSync and Operating System details.

**Comment by dortegat** [comment] 2022-04-12 20:10
yes, I clicked the apply button and also ok.  I reopened and the changes are still not saved.  I am using QGIS 3.22, QFieldSync 4.0.0 and Windows 10

**Comment by suricactus** [comment] 2022-04-12 20:40
Just checked on a windows machine, seems the problem does not exist. Are you sure the expression you wrote is correct? Can you please try with something very simple that is a valid expression?
If it still fails, can you create a new QGIS profile and try QFieldSync from there.

**Comment by ZsanettMed** [comment] 2022-04-12 20:55
Hi @dortegat. I just cheked your issue too. I could not reproduce it neither. Can you let us know what exactly you want to change? Maybe send us both expressions (the current one and the one what you want to modify)?

**Comment by dortegat** [comment] 2022-04-13 06:27
Hi @ZsanettMed,

Screencast attached. https://www.loom.com/share/b275300f230d45fc8588c8998fbc97bc

Expression before: 
`'DCIM/fotos_' || format_date(now(),'yyyyMMddhhmmsszzz') || '.jpg'`

Expression after: 
`'fotos/' || 
attribute(get_feature( 'Inspecciones2022_v2','uuid', "uuid_inspeccion" ), 'gw_cdugh') || 
'_' || format_date(now(),'yyyyMMdd_hhmmss') ||
'_fid_' ||  "fid"  || 
'.jpg'
`
I close and reopen Current Project Settings and this expression remains:
`'DCIM/fotos_' || format_date(now(),'yyyyMMddhhmmsszzz') || '.jpg'`

**Comment by ZsanettMed** [comment] 2022-04-13 08:19
Hey, thanks a lot to share the screencast with us. This helped to reproduce the issue, I guess. There is another way to change the path, can you please try this: click on the layer symbology and then QField, then make your changes.

Please let us know if it works for you. However, we will check why it is not possible to change the path via QField Sync Toolbar. 
![image](https://user-images.githubusercontent.com/83091224/163131721-fbb07d38-c000-4cbe-8efc-e3ad22bf6832.png)

**Comment by dortegat** [comment] 2022-04-13 12:26
Hi, in the way you comment, the path is correctly stored in QGIS Desktop.
But when I export the project to the mobile device and take a photo, it is stored in the default path DCIM/JPEG_202204... and not in the path stored in QGIS Desktop: photos/....

**Closed** 2022-04-19 07:47 UTC
Labels: bug
