### ISSUE TITLE
QFieldSync v3.3.0 failing to load raster files

### ISSUE THREAD

**Issue by sophieoudry** [opengisch/qfieldsync#192] opened 2020-10-01 05:30 UTC
I have upgraded to QFieldSync v3.3.0 and since then, the raster files are not loading on my mobile device. When opening the project, I have a message telling me "the following files can not be loaded. Check them and configure your QGIS project". The problem is encountered only with raster files; vector files load without problem and they appear on the QField app. 

Of course my QGIS project is configured and it worked fine with the previous version. QField app is up to date.

The solution is to uninstall v.3.3.0 and revert back to the previous version and it works.

**Comment by BoswachterMarc** [comment] 2020-10-17 13:24
I experienced the same problem and re-installed the previous version V.3.2.2 as a solution.

[](https://plugins.qgis.org/plugins/qfieldsync/)
![Knipsel](https://user-images.githubusercontent.com/57868975/96338216-c3b7ca80-108c-11eb-8269-08456bbce47d.PNG)

**Comment by nirvn** [comment] 2020-10-17 13:28
@sophieoudry , what kind of raster?

**Comment by nirvn** [comment] 2020-10-17 13:28
@BoswachterMarc , same to you, what kind of raster?

**Comment by BoswachterMarc** [comment] 2020-10-17 13:30
In my case MBtiles (topomap and hillshade)

**Comment by sophieoudry** [comment] 2020-10-17 13:31
@nirvn jpg and tiff

**Comment by nirvn** [comment] 2020-10-17 13:34
I'm pretty sure PR #196 will fix this for you guys.

Can either of you attach a sample raster that's not working here?

**Comment by BoswachterMarc** [comment] 2020-10-17 13:38
Here is one. Thank you ;-)
[Topokaart_ZL15.zip](https://github.com/opengisch/qfieldsync/files/5395773/Topokaart_ZL15.zip)

**Comment by nirvn** [comment] 2020-10-18 02:57
I've tried exporting a test project with the above-attached mbtile raster with PR #196 applied, working flawlessly here. Hope we can push a point release soon, stay tuned.

**Comment by BoswachterMarc** [comment] 2020-11-22 20:02
I still have the problem, although 

1. I tried all recent QFieldSync releases (3.3.1 and 3.4.0) and some old ones (3.1.8 and 3.2.2) but now the problem persists...
2. I cleaned up the whole project and when copying the files manually to the QField map on my mobile, it works fast and smooth... 

But when trying above versions, the sync tool 'package for QField' is greyed out/visible but not available...
![Printscreen](https://user-images.githubusercontent.com/57868975/99915760-e7160b00-2d05-11eb-995d-b76b3c050354.png)

**Comment by meyerlor** [comment] 2020-12-15 14:38
same here - ther earlier workaround (dropping the raster straight from windows file explorer into the QGIS project) does not work anymore. rasters are not compatible for the moment with qfield sync

**Comment by nirvn** [comment] 2020-12-16 02:15
@BoswachterMarc , can you  take a screenshot of the project properties' QField panel? (i.e. where you have a list of all your layers with a combobox list of actions et cie).

**Comment by BoswachterMarc** [comment] 2020-12-18 10:45
@nirvn  Here you are ;-)
![printscreen2](https://user-images.githubusercontent.com/57868975/102606049-7b696700-4126-11eb-82ba-fe4ea220d8fc.png)
![Printscreen](https://user-images.githubusercontent.com/57868975/102606056-7c9a9400-4126-11eb-9465-145874be4cae.png)

**Comment by nirvn** [comment] 2020-12-19 03:25
@BoswachterMarc , are the raster stored in a network drive? Can you paste the raster layer source URI?

**Comment by BoswachterMarc** [comment] 2020-12-19 09:55
@nirvn Initially they were stored on a network drive but recently I started working in Linux Mint and I copied the *.MBTiles to the local folder. The problem was not solved. This morning I rebuild the project 'from scratch' (I exported all the layers to a new Geopackage, copied the raster/*.MBTiles to the new/same folder and made a new project *.qqz importing the styles and map themes).
In the beginning, the 'make package for QField' symbol was still greyed out, but a certain moment It showed up 'colorful' :-)
Nevertheless, the options for the raster files (for exemple the 'Hillshade') are just 'No Action' or 'Remove'. It seems I can't copy them? Under properties of each layer there is a QField section now, but that section is not available under the layer properties of the raster files.
When I run the package for QField, the two raster layers are not copied :-(

![printscreen3](https://user-images.githubusercontent.com/57868975/102686366-98b23a00-41e7-11eb-9b3a-1f7028539acb.png)
![printscreen2](https://user-images.githubusercontent.com/57868975/102686367-994ad080-41e7-11eb-835d-21914de005ae.png)
![printscreen1](https://user-images.githubusercontent.com/57868975/102686368-99e36700-41e7-11eb-8393-5da0da7e7481.png)
![printscreen5](https://user-images.githubusercontent.com/57868975/102686472-50dfe280-41e8-11eb-948e-48fc78cad410.png)
![printscreen4](https://user-images.githubusercontent.com/57868975/102686474-51787900-41e8-11eb-9254-b8ff4bbf967b.png)

**Comment by BoswachterMarc** [comment] 2020-12-19 10:05
@nirvn When I copy my local folder (see printscreen previous post) to my mobile device, the project runs smoothly with the raster files...

**Comment by nirvn** [comment] 2020-12-19 10:45
@BoswachterMarc , can you take a screenshot of the 'Information' panel of your hillshade .mbtiles raster?

**Comment by nirvn** [comment] 2020-12-19 10:46
I'm pretty sure the problem is that those .mbtiles are loaded through the WMS(T)/XYZ provider, not gdal. This will require a small fix on QGIS' side of things.

In any case, awaiting your screenshot :)

**Comment by BoswachterMarc** [comment] 2020-12-19 11:48
The information panel ;-)
![printscreen6](https://user-images.githubusercontent.com/57868975/102688667-7e348c80-41f8-11eb-8dc7-f4e76efcfbaf.png)

**Comment by nirvn** [comment] 2020-12-19 11:56
Ok, good. It'll be fixed in an upcoming release.

In the meantime, here's a workaround: open the mbtiles via the raster panel as you'd open a .tif file for eg.

**Comment by BoswachterMarc** [comment] 2020-12-19 18:54
Ok, and thank you (for the tip/workaround).

**Comment by suricactus** [comment] 2021-10-09 16:51
Fix should have been delivered since long time, close.

**Closed by suricactus** 2021-10-09 16:51 UTC
