### ISSUE TITLE
QField export basemap single layer exports all the layers (literally) instead of a single one

### ISSUE THREAD

**Issue by tdeboss** [opengisch/qfieldsync#212] opened 2021-01-12 23:39 UTC

**Comment by roger1233** [comment] 2021-02-24 16:25
I can confirm this bug. The reason is that "package for QField" calls the processing tool "rasterize"

The package wanted a parameter of LAYER before version 3.16 of QGIS and changed to LAYERS. Qpackage submitted the LAYER argument instead, therefore the rasterize tool would default to rasterize all layers visible, creating this bug.

I submitted a pull request to fix that problem.

**Comment by suricactus** [comment] 2021-02-24 17:44
Thanks to @roger1233 this has been fixed via #220 .

**Closed by suricactus** 2021-02-24 17:44 UTC
