### ISSUE TITLE
QFieldSync 4.0.0 BETA20 crashes when uploading to cloud

### ISSUE THREAD

**Issue by alpinfra** [opengisch/qfieldsync#404] opened 2022-03-09 08:28 UTC
Hi there,

I have developed an input mask for QField mobile device, where the field team can view locally stored JPGs through the attachment widget. I am able to upload them to QFieldCloud, but I cannot view/access them on my mobile device running QField Dev.

It works with regular QField.

I tried to find the locally stored QFieldCloud Project and move the JPG files in the local folder, but cannot find one. Mind that these JPGs are not intended to be edited or synchronized, I just need them copied once to the mobile device and be able to access them from the QField widget.
Also, when taking a picture in the field with the mobile device, synchronization works beautifully!

Any help?

Here is a snippet from the data list from this project, taken from a web browser. The JPGs were clearly uploaded:
![141422498-8888cf8c-1327-4326-90ef-ae557134c890](https://user-images.githubusercontent.com/57482615/157402356-9b6376c8-23e0-412a-a0c7-c2a3e0cf14e1.png)

As from https://github.com/opengisch/QField/discussions/2460

**Comment by alpinfra** [comment] 2022-03-09 08:29
After upgrading QField Sync to v4.0.0-beta20, QGIS crashes in the process of copying the project to a local directory, before uploading it to the cloud.

What I'm doing is:

Open the desired project in QGIS
QFieldCloud Projects Overview -> click Create New Project
Choose how to create a new project -> Convert currently open project to cloud project -> Next
Project Details: select default Project Name (31 chars, no whitespace); leave Project description blank; enter valid yet non-existent local directory to be created; Notice below in green text: The entered path is not an existing directory. It will be created after you submit this form.
Hit Create
When Conversion is at 65% -> QGIS crashes (see crash report below).
One thing worth mentioning is I have meanwhile upgraded QGIS to 3.22.4 (LTR).
[crash_report.txt](https://github.com/opengisch/qfieldsync/files/8212935/crash_report.txt)

**Comment by suricactus** [comment] 2022-03-09 08:36
Thanks for reporting @alpinfra . I have modified the title a little bit, hope you don't mind :)

Can you reliebly reproduce the crash multiple times and also does it happen on other QGIS projects?

**Comment by alpinfra** [comment] 2022-03-09 08:40
Issue reproduced multiple times with the same project. 

Other (large in terms of data volume) projects succeed when converting and uploading...

Below is a screenshot of the data structure for the project that keeps failing.
- Project is stored in the same folder as the Geodata is
- 1 GeoPackage, 1 MBTiles, 5 TIF-grids
- subfolder **JPG** contains 147 jpg's that are required as an attachment, total size = 116MB

When QGIS crashes at the conversion stage, the following files are copied to the local directory:
- Geopackage incl. gpkg-shm and gpkg-wal files,
- MBTiles-file


![Screenshot 2022-03-09 093452](https://user-images.githubusercontent.com/57482615/157404165-711c3550-7673-4c85-bb44-31e45902f7c2.jpg)

**Comment by suricactus** [comment] 2022-03-09 08:54
The crash you have seems to be proejct specific and might be due to QGIS bug itself.

I would suggest to you to remove one layer at a time, then retry to see if crash still happens, and do so until crash doesn't occur.

Looking at the crash report, it seems you need to start from the raster layers.

**Comment by alpinfra** [comment] 2022-03-09 11:09
Thought the same and you are correct. But the issue are not the TIF-grids, but rather the MBTiles-file. When removing it, I can convert and upload the project. Also able to download the project. Yet, I am still not able to view the attachments (JPG).

**Comment by nirvn** [comment] 2022-03-09 11:10
@alpinfra , feel free to attach the mbtiles here so we can replicate your crash.

**Comment by suricactus** [comment] 2022-03-10 08:09
Seems the errro is specific to this particular mbtiles file, so attaching by attaching it here, @alpinfra increases the chances someone looks into this issue.

**Comment by nirvn** [comment] 2022-03-10 11:31
Crash identified and a fix has been submitted to QGIS (https://github.com/qgis/QGIS/pull/47718)

**Comment by nirvn** [comment] 2022-03-11 04:15
Fixed upstream, it'll be OK in the next QGIS 3.24 and LTR point release.

**Closed by nirvn** 2022-03-11 04:15 UTC
Labels: bug, feedback

**Comment by nirvn** [comment] 2022-03-11 04:16
@alpinfra , in the meantime, a work around is to load the .mbtiles through the GDAL provider (instead of drag and dropping the file onto QGIS):
![image](https://user-images.githubusercontent.com/1728657/157801024-25e62339-8317-4e4a-9669-4cd792849ebe.png)
