### ISSUE TITLE
Can't install on Ubuntu 16.10 as QtWebKit is deprecated

### ISSUE THREAD

**Issue by scruss** [opengisch/qfieldsync#37] opened 2017-04-05 20:26 UTC
qfieldsync won't install as it requires qgis2compat, which in turn uses QtWebKit. This has been removed from Qt5, and python-qt4-webkit is no longer available.

**Comment by m-kuhn** [comment] 2017-04-05 21:11
QtWebKit is still available for Qt5.

**Comment by scruss** [comment] 2017-04-05 22:24
Yes, but qgis2compat *explicitly* loads Qt4's version:

    Couldn't load plugin 'qgis2compat' 
    
    ImportError: No module named QtWebKit 
    Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 281, in loadPlugin
        __import__(packageName)
      File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
        mod = _builtin_import(name, globals, locals, fromlist, level)
      File "/home/scruss/.qgis2/python/plugins/qgis2compat/__init__.py", line 51, in 
        import qgis2compat.PyQt
      File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
        mod = _builtin_import(name, globals, locals, fromlist, level)
      File "/home/scruss/.qgis2/python/plugins/qgis2compat/PyQt/__init__.py", line 36, in 
        from QtWebKit import *
      File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
        mod = _builtin_import(name, globals, locals, fromlist, level)
      File "/home/scruss/.qgis2/python/plugins/qgis2compat/PyQt/QtWebKit.py", line 26, in 
        from PyQt4.QtWebKit import *
      File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 572, in _import
        mod = _builtin_import(name, globals, locals, fromlist, level)
    ImportError: No module named QtWebKit
    
    
    Python version: 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914] 
    QGIS version: 2.14.5-Essen Essen, exported 
    
    Python Path:
    /usr/share/qgis/python/plugins/processing
    /usr/share/qgis/python
    /home/scruss/.qgis2/python
    /home/scruss/.qgis2/python/plugins
    /usr/share/qgis/python/plugins
    /usr/lib/python2.7
    /usr/lib/python2.7/plat-x86_64-linux-gnu
    /usr/lib/python2.7/lib-tk
    /usr/lib/python2.7/lib-old
    /usr/lib/python2.7/lib-dynload
    /usr/local/lib/python2.7/dist-packages
    /usr/local/lib/python2.7/dist-packages/Chiplotle-0.4.1-py2.7.egg
    /usr/local/lib/python2.7/dist-packages/descartes-1.0.1-py2.7.egg
    /usr/local/lib/python2.7/dist-packages/esptool-0.1.0-py2.7.egg
    /usr/local/lib/python2.7/dist-packages/noteshrink-0.1.0-py2.7.egg
    /usr/local/lib/python2.7/dist-packages/pcbasic-16.12.0rc0-py2.7.egg
    /usr/local/lib/python2.7/dist-packages/amitools-0.1.0-py2.7-linux-x86_64.egg
    /usr/lib/python2.7/dist-packages
    /usr/lib/python2.7/dist-packages/PILcompat
    /usr/lib/python2.7/dist-packages/gtk-2.0
    /usr/lib/python2.7/dist-packages/ubuntu-sso-client
    /usr/lib/python2.7/dist-packages/wx-3.0-gtk2
    /home/scruss/.qgis2//python
    /home/scruss/.qgis2/python/plugins
    /usr/share/qgis/python/plugins/fTools/tools

**Comment by m-kuhn** [comment] 2017-04-06 06:26
oh right... Debian really caused some huge mess there. I'll have a look.

**Comment by arne1921KF** [comment] 2017-04-10 15:29
Just FTR, so people who search for it end up here more easily, the error message is:
`cannot import QtWdgets`

**Comment by m-kuhn** [comment] 2017-04-12 06:08
Thank you for reporting.

Duplicate of https://github.com/opengisch/qgis2compat/issues/2

Please update qgis2compat to 0.4.6 and restart QGIS. If the problem persists, please open an issue against qgis2compat.

**Closed by m-kuhn** 2017-04-12 06:08 UTC
