### ISSUE TITLE
Python error when creating a basemap with QGIS 3

### ISSUE THREAD

**Issue by Alancowlishaw** [opengisch/qfieldsync#83] opened 2018-07-30 09:57 UTC
I get the following python error when i try to create a new QField project:

```
2018-07-30T10:54:41     WARNING    Traceback (most recent call last):
              File "C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\dialogs\package_dialog.py", line 112, in package_project
              offline_convertor.convert()
              File "C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\offline_converter.py", line 100, in convert
              self.project_configuration.base_map_mupp)
              File "C:/Users/alan.cowlishaw/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\offline_converter.py", line 179, in createBaseMapLayer
              results, ok = alg.run(params, context, feedback)
             AttributeError: 'NoneType' object has no attribute 'run'
```

I have tried using various basemapa and layer combinations and I keep getting the same result. Any ideas?

Thanks, Alan.

**Comment by m-kuhn** [comment] 2018-07-30 10:09
Can you go to the processing options and check if there is a QFieldSync algorithm provider and if it is enabled?

**Comment by m-kuhn** [comment] 2018-07-30 10:10
Wait, you are using the QGIS 3 version... In this case there is no QFieldSync provider. Maybe processing is disabled?

**Comment by m-kuhn** [comment] 2018-07-30 10:32
hmmm... what do you mean with qfieldsync-qgis3 was "false"? was the plugin disabled? in this case, how did you launch the process?

**Comment by Alancowlishaw** [comment] 2018-07-30 10:41
I am not sure.

Here is a screenshot:

![qgis capture](https://user-images.githubusercontent.com/32803497/43393000-14b8ab42-93e5-11e8-997d-94f38bccbc56.JPG)

**Comment by m-kuhn** [comment] 2018-07-30 10:47
Oh, that's not what I meant, sorry.

Go to "Plugins -> Manage and Install Plugins" and check that processing is enabled.

Given that there is no menu point called "Processing" in the options menu on your screenshot, it's very probable it's disabled.

**Comment by Alancowlishaw** [comment] 2018-07-30 10:49
Yep, that sorted it, thankyou. :-)

**Comment by suricactus** [comment] 2021-10-09 17:00
Seems the issue is fixed now. Closing.

**Closed by suricactus** 2021-10-09 17:00 UTC
